Repository JesusV545/GreenUP, pull requests merged in 2023-03, with the labels that each got.

#3 some simple routes for functionality
  Develop/config/connection.js
  Develop/controllers/apis/index.js
  Develop/controllers/apis/userRoutes.js
  Develop/controllers/homeRoutes.js
  Develop/controllers/index.js
  Develop/db/schema.sql
  Develop/utils/withAuth.js
Labels: documentation

#7 Feature/js jump
  Develop/controllers/comments.js
  Develop/public/css/style.css
  Develop/public/pages/reviews.html
  Develop/public/scripts/reviews.js
  Develop/server.js
  Develop/utils/fsUtils.js
  Develop/utils/helper.js
  Develop/utils/uuid.js
  Develop/utils/withAuth.js
Labels: documentation, enhancement

#10 added the js files for login/logout
  Develop/public/js/login.js
  Develop/public/js/logout.js
  Develop/public/js/profile.js
Labels: documentation, enhancement

#14 updated the README file
  Develop/package.json
  Develop/public/js/reviews.js
  README.md
Labels: documentation

#11 Cloudinary package
  Develop/package.json
  Develop/public/pages/reviews.html
  Develop/seeds/productData.json
  Develop/utils/cloudinary.js
  Develop/views/layouts/homepage.handlebars
  Develop/views/layouts/main.handlebars
  Develop/views/layouts/products.handlebars
Labels: documentation, enhancement

#18 Feature/interactive
  Develop/.DS_Store
  config/connection.js
  controllers/api/comments.js
  controllers/api/index.js
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  controllers/index.js
  controllers/productRoutes.js
  db/schema.sql
  models/Carts.js
  models/Comment.js
  models/Order.js
  models/Product.js
  models/User.js
  models/index.js
  package.json
  public/.DS_Store
  public/css/style.css
  public/img/allVeggies.jpg
  public/img/deliveryGreens.jpeg
  public/img/dietGreen.webp
  public/js/login.js
  public/js/logout.js
  public/js/profile.js
  public/js/reviews.js
  public/pages/index.html
  public/pages/reviews.html
  seeds/productData.json
  seeds/seed.js
  seeds/userDate.json
  server.js
  utils/cloudinary.js
  utils/fsUtils.js
  utils/uuid.js
  views/all.handlebars
  views/homepage.handlebars
  views/layouts/homepage.handlebars
  views/layouts/main.handlebars
  views/product.handlebars
  views/products.handlebars
Labels: documentation, enhancement

#23 login & signup rerouting working
  config/connection.js
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  controllers/index.js
  public/js/login.js
  public/js/profile.js
  views/all.handlebars
  views/createAccount.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/signUp.handlebars
Labels: documentation, enhancement

#30 still works but cart js needs work
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  public/js/cart.js
  public/js/login.js
  public/js/profile.js
  server.js
  views/aboutUs.handlebars
  views/cart.handlebars
  views/layouts/main.handlebars
  views/product.handlebars
  views/products.handlebars
Labels: bug, documentation, enhancement
